apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 9.3.0 
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch
    logs:
      elasticsearchRefs:
        - name: elasticsearch
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
  - name: stable 
    count: 1
    config:
      node.roles: ["master", "data", "ingest"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi  
              cpu: 1  
            limits:
              memory: 2Gi 
              cpu: 2  
    volumeClaimTemplates:  
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: small 
    count: 1 
    config:
      node.roles: ["data", "ingest"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 256Mi
              cpu: 1
            limits:
              memory: 256Mi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi  
